### ISSUE TITLE
Add bs_call to bioconda

### ISSUE THREAD

**Issue by karl616** [heathsc/bs_call#1]
Hi,
I want to add bs_call to bioconda and have set up a recipe based on v2.0.1:

https://github.com/karl616/bioconda-recipes/commit/8b2c4968c71f1c440e95db63022d6e84a6943ff5

As a courtesy, before I merge it in, I wanted to ask if there are objections against this?
Personally, I would find it practical to have access to bs_call through conda.

**Comment by karl616** [comment]
Doing this, I have problem with openmp for macos. Is this something that is known?

**Comment by heathsc** [comment]
No objections at all.

Simon

**Comment by heathsc** [comment]
It can be disabled - it has little to no effect.  The configure script should do this automatically.

Simon

**Comment by karl616** [comment]
OK, then my problem is that I went ahead with the release version (v2.0.1). I didn't get the configure script to work there.
Would it be possible to have a newer release? Ultimately based on the latest commit, the one that is linked from gemBS. That is my final target...

**Comment by karl616** [comment]
(The reason the configure script of v2.0.1 fails is a missing Makefile.mk.in)

**Comment by heathsc** [comment]
Odd - I get src/Makefile.mk.in and GEMTools/Makefile.mk.in.  There shouldn’t be any difference between the bs_call version in gemBS and the ‘standalone’ version.

Simon

**Comment by karl616** [comment]
That is true. But for bioconda I must work with releases:
https://github.com/heathsc/bs_call/releases

and in the commit tagged v2.0.1 src/Makefile.mk.in is missing.

It was fixed here:
https://github.com/heathsc/bs_call/commit/03dfcf9d4854f3b163a1b5c657f617779e68ceaf

**Comment by heathsc** [comment]
OK, I have made a new release - v2.0.2

**Comment by karl616** [comment]
Thanks!

**Comment by karl616** [comment]
I have merged in the bs_call recipe into bioconda. It worked better with the updated version but I ended up forcibly disabling openmp for macos as I was unable to get it working otherwise.
Anyhow, bs_call is now present in bioconda and with the repository active it can be installed with:
`conda install bs_call`
I'll close this issue.
